# Generated by Django 3.2.8 on 2021-10-30 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=None, max_length=255, verbose_name='Endereço')),
                ('number', models.CharField(default=None, max_length=16, verbose_name='Número')),
                ('complement', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Complemento')),
                ('neighborhood', models.CharField(default=None, max_length=50, verbose_name='Bairro')),
                ('zip_code', models.CharField(default=None, max_length=12, verbose_name='CEP')),
                ('city', models.CharField(default=None, max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(default=None, max_length=2, verbose_name='UF')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=150, verbose_name='Nome completo')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='E-Mail')),
                ('birthday', models.DateField(default=None, verbose_name='Data de nascimento')),
                ('cpf', models.CharField(default=None, max_length=16, verbose_name='CPF')),
                ('rg', models.CharField(default=None, max_length=20, verbose_name='RG')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='user.address', verbose_name='Endereço do Acervo')),
                ('second_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_user_address', to='user.address', verbose_name='Segundo Endereço do Acervo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
