# Generated by Django 3.2.8 on 2021-10-31 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211030_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='second_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_user_address', to='user.address', verbose_name='Segundo Endereço do Acervo'),
        ),
    ]
