# Generated by Django 3.2.8 on 2021-11-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_second_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Foto'),
        ),
    ]
