# Generated by Django 3.2.8 on 2021-10-30 23:34

from django.db import migrations, models
import django.db.models.deletion


def create_activities(apps, schema_editor):
    print(">> Criando atividades do CR...")

    Activity = apps.get_model('manager', 'Activity')

    activity_list = [
        "Tiro Desportivo",
        "Caça",
        "Colecionamento"
    ]

    for activity in activity_list:
        Activity.objects.get_or_create(name=activity)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, unique=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='Número de protocolo')),
                ('entry_date', models.DateField(default=None, verbose_name='Data de entrada')),
                ('service', models.CharField(choices=[('cr_concession', 'Concessão de CR'), ('purchase_authorization', 'Autorização de Compra'), ('craf', 'CRAF'), ('gt', 'Guia de Trânsito'), ('register', 'Apostilamento')], default=None, max_length=100, verbose_name='Serviço')),
                ('status', models.CharField(choices=[('deferred', 'Deferido'), ('in_analysis', 'Em Análise'), ('pending', 'Pendente'), ('rejected', 'Indeferido'), ('refunded', 'Restituído'), ('other', 'Outro')], default='pending', max_length=16, verbose_name='Situação do processo')),
                ('reason', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Motivo')),
                ('om', models.CharField(default=None, max_length=100, verbose_name='OM')),
                ('gru_status', models.CharField(choices=[('pending', 'Pendente'), ('payed', 'Paga'), ('other', 'Outro')], default='pending', max_length=10, verbose_name='Situação da GRU')),
                ('gru_compensation_date', models.DateField(blank=True, default=None, null=True, verbose_name='Data da compensação da GRU')),
            ],
        ),
        migrations.CreateModel(
            name='CR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=None, max_length=16, verbose_name='Número do CR')),
                ('expiration_date', models.DateField(default=None, verbose_name='Data de validade')),
                ('rm', models.CharField(choices=[('1', '1ª RM'), ('2', '2ª RM'), ('3', '3ª RM'), ('4', '4ª RM'), ('5', '5ª RM'), ('6', '6ª RM'), ('7', '7ª RM'), ('8', '8ª RM'), ('9', '9ª RM'), ('10', '10ª RM'), ('11', '11ª RM'), ('12', '12ª RM')], default=None, max_length=2, verbose_name='SFPC de vinculação (RM)')),
                ('activities', models.ManyToManyField(to='manager.Activity', verbose_name='Atividades Autorizadas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile', verbose_name='Usuário')),
            ],
        ),
        migrations.RunPython(create_activities),
    ]
