# Generated by Django 3.2.8 on 2021-10-31 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20211030_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200, verbose_name='Nome')),
                ('manufacturer', models.CharField(default=None, max_length=200, verbose_name='Fabricante')),
                ('pce_type', models.CharField(choices=[('firearm', 'Arma de Fogo'), ('ammo', 'Munição'), ('reloading_tool', 'Máquina de Recarga'), ('dies', 'Dies'), ('other', 'Outro')], default=None, max_length=50, verbose_name='Tipo de PCE')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'PCE',
                'verbose_name_plural': 'PCEs',
            },
        ),
        migrations.AddField(
            model_name='process',
            name='pce',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.pce', verbose_name='PCE'),
        ),
    ]
