# Generated by Django 3.2.8 on 2021-10-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20211030_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='service',
            field=models.CharField(choices=[('cr_concession', 'Concessão de CR'), ('address_update', 'Atualização de Endereço do Acervo'), ('doc_update', 'Atualização de Documento Pessoal'), ('activity_update', 'Atualização de Tipo de Atividade'), ('cr_cancel', 'Cancelamento de CR para Pessoa Física'), ('second_address_add', 'Inclusão de 2º Endereço de Acervo'), ('purchase_authorization', 'Autorização de Compra'), ('craf', 'CRAF'), ('gt', 'Guia de Trânsito'), ('register', 'Apostilamento'), ('import_authorization', 'Autorização de Aquisição de PCE por Importação (CII)'), ('procurator_add', 'Instituir Procurador para Pessoa Física'), ('revalidation', 'Revalidação para Pessoa Física')], default=None, max_length=100, verbose_name='Serviço'),
        ),
    ]
